name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - prod

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

defaults:
  run:
    working-directory: "./packages/backend"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (opcional)
        run: pytest # si tienes tests

      - name: Upload artifact for deployment
        run: |
          zip -r app.zip . -x '*.git*'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./app.zip
