name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - prod

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

defaults:
  run:
    working-directory: "./packages/backend"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Obtener el codigo fuente del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Preparar Python en el runner
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Instalar dependencias del proyecto python FastApi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Correr tests
      - name: Run tests
        run: pytest # si tienes tests

      # Subir artefacto para el despliegue
      - name: Upload artifact for deployment
        run: |
          zip -r app.zip . -x '*.git*' '*.venv*' '__pycache__/*' '*.pyc' '*.pyo'

      # Desplegar a Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./packages/backend/app.zip
